FROM opensuse/tumbleweed

ENV ARCH=x86_64

RUN zypper in -y \
    cmake gcc-c++ libcurl-devel libopenssl-1_1-devel automake libtool \
    patch wget vim desktop-file-utils glib2-devel cairo-devel librsvg-devel \
    fuse-devel libqt5-qtbase-devel git findutils

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

ENV APPIMAGE_EXTRACT_AND_RUN=1
